### ISSUE TITLE
3D coordinate generation too slow for import line format

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/mongochemserver#106]
If you import something larger, such as caffeine, using the import_structure API the request thread times out. We probably need to move the generation of 3D coordinates to something asynchronous to avoid time outs, and add support for uploading 3D structures in CJSON, etc.

**Comment by psavery** [comment]
@cryos I just noticed that the pybel API allows us to set the force field and the number of steps [here](http://openbabel.org/docs/dev/UseTheLibrary/Python_PybelAPI.html#pybel.Molecule.make3D).

I wonder if we could make the force field optimization optional?

**Comment by cryos** [comment]
We need to consider ways to make the whole thing asynchronous, this is just one option too, and we want to add ANI soon that will use trained models to predict structure.

**Comment by psavery** [comment]
@cryos For initially creating the molecule, I think the only part that needs the 3D coordinates is the cjson. If 2D coordinates are provided, should I still create the whole molecule (except the cjson) and return it, and then the cjson will be created later in the background thread?

**Comment by psavery** [comment]
I think this should now be fixed. Closing. We can re-open if there are issues.
