### ISSUE TITLE
Open Babel bond perception doesn't work for water

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/mongochemserver#145]
While I was testing the new Open Babel flask images, I started noticing that, despite running the Open Babel bond perception, the psi4 output for water would not have bonds.

I investigated it further. I noticed a few things:
1. It still happens with all of our default up-to-date configurations of mongochemdeploy, mongochemserver, and the docker images. So the Open Babel flask image is probably not the issue.
2. Bonds are correctly perceived for methane (both with the Open Babel flask image, and with the direct API calls).
3. It also happens when I try to perceive the bonds with a python script.

The attached [psi4_h2o.sdf.gz](https://github.com/OpenChemistry/mongochemserver/files/3522957/psi4_h2o.sdf.gz) file was generated in mongochemserver (it used avogadro to convert the cjson output of our psi4 docker image to sdf). If you open it in Avogadro2 and click "Build"->"Bond"->"Bond Atoms", it perceives the bonds correctly. However, if I try to perceive the bonds with Open Babel, the following happens:
```
import pybel
  
gen = pybel.readfile('sdf', 'psi4_h2o.sdf')
mol = next(gen)
obmol = mol.OBMol

print('Original number of bonds is:', obmol.NumBonds())
# Output: 0

obmol.ConnectTheDots()
obmol.PerceiveBondOrders()

print('After connecting the dots and perceiving bond orders, '
      'the number of bonds is:', obmol.NumBonds())
# Output: 0
```

I do not know if this is a glitch only for water, or other molecules as well. 

<strike>
However, I am wondering if we should go ahead and try to start using Avogadro2 for the bond perception. Currently, our bond perception pathway looks like this:

**cjson** ---*avogadro convert*---> **sdf** ---*openbabel bond perception*---> **sdf** ---*avogadro convert*---> **cjson**

If we used Avogadro2, it would look like this:

**cjson** ---*avogadro bond perception*---> **cjson**
 
[perceiveBondsSimple()](https://github.com/OpenChemistry/avogadrolibs/blob/66b8aadab8a8fe748247688b6153bda1409ab5a6/avogadro/core/molecule.h#L565) is a member of the Avogadro2 Molecule class, and we could add a definition in pybind11 [here](https://github.com/OpenChemistry/avogadrolibs/blob/66b8aadab8a8fe748247688b6153bda1409ab5a6/python/core.cpp#L44). I think we could start using it if we did that.

It looks like the "Build"->"Bond"->"Bond Atoms" action in Avogadro2 actually calls [this function](https://github.com/OpenChemistry/avogadrolibs/blob/66b8aadab8a8fe748247688b6153bda1409ab5a6/avogadro/qtplugins/bonding/bonding.cpp#L105), but it mentions it is largely reproduced from `Molecule::perceiveBondSimple()`.

</strike>

The above section was deleted because Avogadro2 can only do single bonds.

**Comment by psavery** [comment]
(By the way, if I move the hydrogen atoms closer to the oxygen atom by changing their values in the sdf file, Open Babel still does not perceive the bonds, so it does not appear to be some kind of tolerance issue).

**Comment by ghutchis** [comment]
SDF files are supposed to already have bonds...

**Comment by psavery** [comment]
Thanks for the help, Geoff!

I put up a PR to fix this issue. Our new pathway for autodetecting bonds when we are dropping all prior bonding info looks like this:

**cjson** ---*avogadro convert*---> **xyz** ---*openbabel bond perception*---> **sdf** ---*avogadro convert*---> **cjson**

**Comment by cryos** [comment]
Much better, sorry I should have caught that SDF was being used for input...
