### ISSUE TITLE
Molecule Access Levels

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/mongochemserver#155]
This issue is intended to bring up some general discussion on the molecules' access levels.

Currently, when a molecule gets created, its access level is set [by default to private](https://github.com/OpenChemistry/mongochemserver/blob/d12bd6d5b3ddb00259347f7f7d4a128c58532f47/girder/molecules/molecules/molecule.py#L140). Should the default potentially be public instead?

Access levels are currently not being enforced for the general GET `/molecules` endpoint, so all molecules can be searched for. However, access levels are enforced for GET `/molecules/{id}`. I ran into this as an issue when trying to access a molecule by its id in Avogadro2: without logging in, a user can search for a molecule, but the molecule can't be downloaded until they log in. It would be nice to be able to use this endpoint by default, and maybe one way we can do it is by making the molecule access level public by default.

However, I did notice that we can download the cjson via GET `/molecules/{id}/{format}`, because that does not have access controls. However, it would be nice to be able to get both the cjson and molecule properties in one rest call, rather than separate ones.

Anyways, I guess I just want to know if we should make molecules public by default so that they can be more easily accessed without logging in via software such as Avogadro2.

**Comment by cjh1** [comment]
Yes it would be good to discuss access control. In the past everything has been tried as public, but it appears we now have a bit of a mix. I think we should discuss the model we want here and then fix things up. This goes for calculation and other collections as well.

**Comment by cryos** [comment]
The primary goal is to create a server where everything is public, and that should be our default. We would like to support access control, and offer user/group access if possible as well as it would aid in other use cases. I think making all molecules public by default is preferable, we should fix the case where you can find a molecule but not download it.
