### ISSUE TITLE
New API Key Interface: "You must be logged in"

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/mongochemserver#157]
If I use the new API key interface in mongochemclient to create an API key for use in Avogadro2, I am able to authenticate and receive a girder token with the API key, but when I use this token for things that require login such as `POST /molecules`, I get an error back from girder telling me that I must be logged in. This seems to happen regardless of the "Permission Scope" settings I choose when creating the API key.

Any ideas on what might be wrong? I don't get this error if I create the API key using the girder web interface.

@cjh1 @bnmajor

**Comment by cjh1** [comment]
@psavery I would check the permission scope of a key your create using girder and one created by mongochemclient and see what the difference it.

**Comment by psavery** [comment]
I did, and that was insightful.

It looks like I always get that error unless `Allow all actions on behalf of my user` is checked. If I  check "Only allow specific permissions for this key", I will always get the error, even if every permission box is checked.

**Comment by cjh1** [comment]
I think the access decorators are probably wrong for these endpoints.
