### ISSUE TITLE
POST /molecules/conversions/{output_format} not working

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/mongochemserver#158]
`POST /molecules/conversions/{output_format}` does not seem to work. If I try to use it, I always get this response, even for acceptable formats:

```
{
  "message": "Output output_format not supported.",
  "type": "rest"
}
```

This endpoint might be really useful for Avogadro2, so it might be good to fix it.

**Comment by psavery** [comment]
Also, it looks like it was originally designed to only be used with a girder `fileId`. It would probably be good if we can put the input data into the POST data as well, like we do when creating a molecule. Something like this:

```
{
  "cjson": ...
}
```

**Comment by bnmajor** [comment]
The newest changes in the endpoint fix the error that caused the "output_format not supported" exception to be thrown every time. Conversions also now work with cjson as well as a fileId.

**Comment by psavery** [comment]
This is working great. Thank you, @bnmajor!
