### ISSUE TITLE
Errors when submitting more than the "maxRunning" number of jobs

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/mongochemserver#179]
If you submit more jobs at the same time than the `maxRunning` number of jobs (which [defaults to 5 in openchemistrypy](https://github.com/OpenChemistry/openchemistrypy/blob/e6950ef688dc5cd83cb0e95c110fc2079f13e971/openchemistry/_utils.py#L21)), then every job that finishes until there are `maxRunning` number of jobs left will appear to fail with errors like those given at the bottom.

However, it looks like the jobs that report failures do, in fact, succeed, but that the [PendingCalculationResultWrapper](https://github.com/OpenChemistry/openchemistrypy/blob/e6950ef688dc5cd83cb0e95c110fc2079f13e971/openchemistry/_calculation.py#L128) incorrectly thinks that the job failed. If you re-run the code to get the result (such as `result = mol.optimize(image_name, input_parameters)`), then it appears that there are no problems.

I'm not sure exactly where the issue might lie. It may partly lie [here](https://github.com/OpenChemistry/mongochemserver/blob/39252f89929be76ee742f3a9ad1461dfd51e026d/girder/queues/queues/models/queue.py#L165-L218), where the `maxRunning` parameter is used. Or it might lie in the [PendingCalculationResultWrapper](https://github.com/OpenChemistry/openchemistrypy/blob/e6950ef688dc5cd83cb0e95c110fc2079f13e971/openchemistry/_calculation.py#L128).

![Screenshot from 2020-02-06 16-18-55](https://user-images.githubusercontent.com/9558430/73979635-80ea0400-48fc-11ea-9db3-c098c76f59a0.png)

Output

```
Preparing job to obtain the container description.
Submitting job to obtain the container description.
Processing the output of the container description job.
Setting up the calculation input files.
Creating openchemistry/torchani job
Uploading the input files to the cluster.
Submitting job 5e3c80c6e60637d8d4d36be7 to the queue.
Submitted job 5e3c80c6e60637d8d4d36be7 to cluster.
Processing the results of the calculation.
Uploading the results of the calculation to the database.
Done!
An HttpError was raise in task_success_handler for task '5e3c80dce60637d8d4d36c5a' the response text was:
{"message": "RuntimeError: RuntimeError('OrderedDict mutated during iteration')", "trace": ["<FrameSummary file /girder/girder/api/rest.py, line 629 in endpointDecorator>", "<FrameSummary file /girder/girder/api/rest.py, line 1212 in PATCH>", "<FrameSummary file /girder/girder/api/rest.py, line 946 in handleRoute>", "<FrameSummary file /girder/girder/api/access.py, line 89 in wrapped>", "<FrameSummary file /girder/girder/api/rest.py, line 430 in wrapped>", "<FrameSummary file /girder/girder/api/rest.py, line 400 in wrapped>", "<FrameSummary file /cumulus/girder/taskflow/taskflow/tasks.py, line 72 in update>", "<FrameSummary file /cumulus/girder/taskflow/taskflow/models/task.py, line 132 in update_task>", "<FrameSummary file /cumulus/girder/taskflow/taskflow/models/taskflow.py, line 276 in update_state>", "<FrameSummary file /girder/girder/events.py, line 285 in trigger>"], "type": "internal", "uid": "920ed220-6ab9-4da5-91d2-b1a1e3892a1d"}
```

**Comment by psavery** [comment]
[Here is a sample ipynb file](https://github.com/OpenChemistry/mongochemserver/files/4167841/sample_error.ipynb.gz) that produces the error.

**Comment by cryos** [comment]
This will probably need some input from @cjh1, I am glad it was easy to reproduce. We should prioritize getting this fixed up.

**Comment by cjh1** [comment]
I think this is a problem with up stream Girder, I will see what we can do to fix it up.

**Comment by cjh1** [comment]
This should be resolved by: https://github.com/girder/girder/pull/3199
