### ISSUE TITLE
Name search should use contains, not starts with

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/mongochemserver#185]
The current name search only checks what a name starts with, it should look at what the name contains. For example, 4-methylbenzenethiol should return when I search for methyl, benzene, and thiol.

**Comment by psavery** [comment]
While we're fixing this, let me ask if formula is fine. Formula is currently requiring an exact match, except it is case insensitive. Is that fine?

Name will also be a case insensitive search.

**Comment by cryos** [comment]
I think ideally they should both be case insensitive, I think formula and name should look at contains primarily as it is the most generally useful. If we get fancy exact matches may be desirable later, but we are often looking for fragments that match in my opinion.

**Comment by cjh1** [comment]
Using contains will mean mongo will not be able to use an index, I think this is why restricted it to a prefix search.

**Comment by cryos** [comment]
It would be better to get a slower result that is more useful, looking at https://docs.mongodb.com/manual/text-search/ it looks like they tokenize, which won't help us here. We could offer an exact match, but I think searching for fragments on any interesting collection is necessary and we need to figure out how to support it even if we lose index support/speed up.
