### ISSUE TITLE
Simplify requests needed to submit a calculation

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/mongochemserver#187]
There are unfortunately many requests (about 6) required to submit a calculation. And this series of requests to submit a calculation has been repeated in many languages:

1. [Python](https://github.com/OpenChemistry/openchemistrypy/blob/b3cedb848832f74d282d6066fc8dd839c3d6b3fb/openchemistry/_calculation.py#L174-L231)
2. [Javascript](https://github.com/OpenChemistry/oc-web-components/blob/0b198282fcef8010211a1ed873f6e9fd47d3ec93/packages/sagas/src/index.js#L360-L415)
3. [C++](https://github.com/OpenChemistry/avogadrolibs/blob/cdfdf9bd8821ff8a503ff0431ba2379bf218000f/avogadro/qtplugins/mongochem/calculationsubmitter.cpp#L60-L472)

We should really move all of the work done in these requests to the server, and then make a single REST endpoint for submitting a calculation, so that it will be much easier for clients.

**Comment by cryos** [comment]
Yes, I think this is a big priority - the core logic must be on the server side. Duplicating it across languages leads to possible differences in the implementations, and increases maintenance burden.

**Comment by psavery** [comment]
The [python](https://github.com/OpenChemistry/openchemistrypy/commit/c63a21910515f060618c484a8f9fbccb88efbfa0) and [javascript](https://github.com/OpenChemistry/oc-web-components/pull/136/commits/a61efe11125b949e37a85ee169deb6a30fd5a63a) versions of this have been greatly simplified because of the changes.

It would be nice to change it in Avogadro2 sometime as well.
