### ISSUE TITLE
We currently have two keys for ids 'id' and '_id'

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/mongochemserver#33]
This is confusing! ( it confused me ) I suggest we standardize on _id ( so we don't have to worry about converting two and from mongo )

**Comment by cryos** [comment]
Agreed, no strong preference on which one here but let's stick to one.

**Comment by cjh1** [comment]
I think in the past we thought 'id' was nicer for an external interface, so we didn't bleed mongo details into the API, but I don't think is worth effort of the extra conversions ... and some clearly slipped through the net .

**Comment by cryos** [comment]
That is a good point, but agreed probably not worth the effort. We can always come back to this if it looks like more of an issue - I hate bleeding too much of the Mongo details through so it was probably me.

**Comment by dgasmith** [comment]
As a note `_id` comes out of Mongo as a ObjectId. It may be worth considering having `id` be the string form of this as tracking ObjectIds around can cause some awkward problems. Conversion to and from these objects is cheap compared to accessing data to/from MongoDB.

**Comment by cjh1** [comment]
@dgasmith `_id` is indeed coming from mongo and in our endpoint they are indeed strings, we have code to do the necessary conversions. I think we have settled on `_id`.  We should clean up any references to `id` and then close this off.
