### ISSUE TITLE
Rework reverted commits

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/mongochemserver#67]
Look at these reverted commits and rework refactor. 

44cd4c9cf9a0f5f428d0ac485d6f5a7a8f8133da
d7f0daff7f3fe8306d9b2a758b364a958fee0c37
1b2882b0d21262db24973e87a91d17318d5a0c5f

**Comment by psavery** [comment]
@cjh1 Let me know if you want me to take a look at the issues here as well.

**Comment by cjh1** [comment]
@psavery Thanks Patrick, we will dig into it, we just need to understand what broken the calculation ingestion code, the rest of the changes are good.

**Comment by cjh1** [comment]
Done
